// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYCZgGH-51VEhmz3r50E6w1qQuHES2U58',
    appId: '1:1885056204:web:21f9970d9eb4bcb757a669',
    messagingSenderId: '1885056204',
    projectId: 'cataractapp-ae8f5',
    authDomain: 'cataractapp-ae8f5.firebaseapp.com',
    databaseURL: 'https://cataractapp-ae8f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cataractapp-ae8f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Uz3etFZPDAfxrM9LYtHRpKpSZs9nVu8',
    appId: '1:1885056204:android:773260921c04c2b757a669',
    messagingSenderId: '1885056204',
    projectId: 'cataractapp-ae8f5',
    databaseURL: 'https://cataractapp-ae8f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cataractapp-ae8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWAfWvZKCFRotQ4zKZmS9zsJ6-NEYRq0I',
    appId: '1:1885056204:ios:7f8ce28df15d3f7a57a669',
    messagingSenderId: '1885056204',
    projectId: 'cataractapp-ae8f5',
    databaseURL: 'https://cataractapp-ae8f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cataractapp-ae8f5.appspot.com',
    iosBundleId: 'com.example.eyedetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWAfWvZKCFRotQ4zKZmS9zsJ6-NEYRq0I',
    appId: '1:1885056204:ios:7f8ce28df15d3f7a57a669',
    messagingSenderId: '1885056204',
    projectId: 'cataractapp-ae8f5',
    databaseURL: 'https://cataractapp-ae8f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cataractapp-ae8f5.appspot.com',
    iosBundleId: 'com.example.eyedetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYCZgGH-51VEhmz3r50E6w1qQuHES2U58',
    appId: '1:1885056204:web:60011e81890c4fd857a669',
    messagingSenderId: '1885056204',
    projectId: 'cataractapp-ae8f5',
    authDomain: 'cataractapp-ae8f5.firebaseapp.com',
    databaseURL: 'https://cataractapp-ae8f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cataractapp-ae8f5.appspot.com',
  );
}
